#!/bin/sh
ns_flag=''
kube_config=''
configmap=''
label=''
multiple_possible=''

# Loop through options to grab what we need
while test $# -gt 0; do
  case "$1" in
    -n|--namespace )
      shift
      ns_flag=$1
      shift
    ;;
    -k|--kubeconfig )
      shift
      kube_config=$1
      shift
    ;;
    -l|--label )
      shift
      label=$1
      shift
    ;;
    -* )
      echo "Option $1 not supported, run 'kubectl viewconfig help' for available options and examples."
      exit 1
    ;;
    help )
      echo "kubectl viewconfig options:\n\t-n (or --namespace): specify the namespace context\n\t-k (or --kubeconfig): specify the kubeconfig context\n\t-l (or --label): specify a label to use for grabbing configmaps' contents\nkubectl viewconfig examples:\n\tkubectl viewconfig -k ~/mykubeconfig -n mynamespace myconfigmapname\n\tkubectl viewconfig -k ~/mykubeconfig -n mynamespace -l app=helloworld"
      exit 0
    ;;
    * )
      configmap=$1
      shift
    ;;
  esac
done

# Start with base command
kubectl_command="kubectl get configmap "

# Exit if no configmap name provided
if [[ $configmap != '' ]]; then
  kubectl_command+="${configmap} "
  if [[ $label != '' ]]; then
    echo "ERROR: Both configmap name and label provided. Only one of these options can be passed in a single command.\nRun 'kubectl viewconfig help' for available options and examples."
    exit 1
  fi
else
  if [[ $label != '' ]]; then
    kubectl_command+="-l $label "
    multiple_possible="true"
  else
    echo "ERROR: No configmap name provided, run 'kubectl viewconfig help' for available options and examples."
    exit 1
  fi
fi

# Tack on ns flag as needed
if [[ $ns_flag != '' ]]; then
  kubectl_command+="-n ${ns_flag} "
fi

# Tack on kube config flag as needed
if [[ $kube_config != '' ]]; then
  kubectl_command+="--kubeconfig ${kube_config} "
fi

# Check if the configmap exists
if [[ ! $($kubectl_command 2> /dev/null) ]]; then
  echo "ERROR: configmap not found, run 'kubectl viewconfig help' for available options and examples."
  exit 1
fi

# Add our fancy dump of config
if [[ $multiple_possible == "true" ]]; then
  kubectl_command+="-o go-template='{{range \$configmap,\$contents := .items}}{{printf \"------\nConfigmap \`%s\`: \n------\n\" \$contents.metadata.name}}{{range \$k,\$v := \$contents.data}}{{printf \"Key \`%s\`: \n---\n\" \$k}}{{\$v}}{{\"\n\n\"}}{{end}}{{end}}'"
else
  kubectl_command+="-o go-template='{{printf \"------\nConfigmap \`%s\`: \n------\n\" .metadata.name}}{{range \$k,\$v := .data}}{{printf \"Key \`%s\`: \n---\n\" \$k}}{{\$v}}{{\"\n\n\"}}{{end}}'"
fi

# Execute
eval $kubectl_command