#!/bin/sh
ns_flag=''
kube_config=''
secret=''

# Loop through options to grab what we need
while test $# -gt 0; do
  case "$1" in
    -n|--namespace )
      shift
      ns_flag=$1
      shift
    ;;
    -k|--kubeconfig )
      shift
      kube_config=$1
      shift
    ;;
    -* )
      echo "Option $1 not supported, run 'kubectl viewsecret help' for available options and examples."
      exit 1
    ;;
    help )
      echo "kubectl viewsecret options:\n\t-n (or --namespace): specify the namespace context\n\t-k (or --kubeconfig): specify the kubeconfig context\nkubectl viewsecret example:\n\tkubectl viewsecret -k ~/mykubeconfig -n mynamespace mysecretname"
      exit 0
    ;;
    * )
      secret=$1
      shift
    ;;
  esac
done

# Start with base command
kubectl_command="kubectl get secret "

# Exit if no secret name provided
if [[ $secret != '' ]]; then
  kubectl_command+="${secret} "
else
  echo "ERROR: No secret name provided, run 'kubectl viewsecret help' for available options and examples."
  exit 1
fi

# Tack on ns flag as needed
if [[ $ns_flag != '' ]]; then
  kubectl_command+="-n ${ns_flag} "
fi

# Tack on kube config flag as needed
if [[ $kube_config != '' ]]; then
  kubectl_command+="--kubeconfig ${kube_config} "
fi

# Check if the secret exists
if [[ ! $($kubectl_command 2> /dev/null) ]]; then
  echo "ERROR: Secret not found, run 'kubectl viewsecret help' for available options and examples."
  exit 1
fi

# Add our fancy decode magic
kubectl_command+="-o go-template='{{range \$k,\$v := .data}}{{printf \"%s: \n---\n\" \$k}}{{if not \$v}}{{\$v}}{{else}}{{\$v | base64decode}}{{end}}{{\"\n\"}}{{end}}'"

# Execute
eval $kubectl_command